language: go
go:
- '1.5'
install:
- go get -d -v ./...
- go build -v
deploy:
  provider: launchpad
  slug: "~cha87de/kvmtop/trunk"
  skip_cleanup: true
  on:
    branch: pkg-testing
  oauth_token_secret:
    secure: 2YBgUUwPk27ME6a48TGbIzf3cS85Ujvcl9dfQlqhNMf7+WNV8wOhZzfK77WPsmNdF82ccVZvzM7BowYRGPBJBTHigP1FuouHP1/rFe9XQFYoQoYnmwJly80zuo8sWGnqeg39/puNsNIovRX8CRtDF3aA0Vkr43ovdW0bhDZIObplgVE4TQx2owbcHFZhzGGX1TQlLkDYaQS5HQUftyAy1IYjZ+vMLVkSOCZKlsUPdv/KusF9L4ei8HLpUIQVgVDG6nLeW3rVz4eQ1ecRTS49j9RRGyWtKnu7m75Ivnlt5PKrNI5Bvw+46099y+dyJuNk1TJtan5BOiUv3Tc9w55A3fxSBucViX40fzIkBItFAG3NZhxYdpFspS++zGelqoBFJRjckAXoLDkqiUvL0gdtDavkZTXZ3JsJgJtIWRPMm27nbJwqzCyuQuwqRpfuk8pgW7tCsxJqpanUyuAnaTe4t7I7Y80W3HFwVL7APcsMv4CUMvPePStcHZfZyGQzr0Ldf9YKXP4GZwB7nfbEk6qNfSsd0mTvz92ebh1Df1uHohA+3XQ+shgmfem33Q/uqV2fsDVdjKgwzvC3sAn85SNbXADgQMHq18q6QfK9wPmIaMP5u3pY9VKnxqQKXhI504LKSAEsjIivF8i5OnUErabMEiXE4SEcAMrJ/8VTwr7rYHk=
  oauth_token:
    secure: uMXwcGBTcJK89ZL4Zy+PQlz7Ru5FFFHDvmoxqditrxsyY6f1sSU+kra7siqGLFRPUG30hpRZR6tfTMaumm/Wk7CTkC9SVmv/4bMz5K4wyudObX0nDNotv/x7swO5HKFiqVuk5SR7ppHbacgC6Fg8GPmzWOhy6jLW5nTDwUZTau5qoo3RsJpoJQ1cioPx7KlnFr0JD3YtEfk1jvHWS9f1zvdNy7bwdsTdznaD9/PQ0k/Zz2ztWAc0teUptSa47Y/QP31erqfJKaUJTm3x/LP2z8o68LMNJu8XOMjIyq3uAXmYrZHpMwPxGLL9L12i1TSzUzRwu5w7PvBx7rjyej2b5P9durKXiA8kOVlfFN7a5dge/O5Gcu8LhBPONJ/O3/8LAATYkTbN1RRQq2Oz2pVK0raZV1FHwIyZWBkig+vsP4a8tzhkR/BdXEE9uDcrO5nkzWxrq0DXfGK/BvyEGginCyEb6hQlEl0ZRJ7f/4yYKEy2i8Mvn1Bxeeclw2xblHO8wG9R6cpxhiJFPrU2dQdLUxhBVi0me3YApBHI1m2CJo3pm0FZko6MLYStGm40aldgpF3vL1hLsVCOO3TKJyKx4EYQ1Dsbhdw88aMctD+hQgFHoabt1CQYj0wlOJf4uqn8g1gPo0qNKdF2hjxYQazd3FP5ZESoiZBiF3c6XLOrPB4=
